---

- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart netdata
  service:
    name: netdata
    state: restarted
    enabled: true

- name: start netdata
  service:
    name: netdata
    state: started
    enabled: true

- name: stop netdata
  service:
    name: netdata
    state: stopped
    enabled: true
